# Generated by Django 6.0.6 on 2026-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpackage',
            name='override_max_file_size_mb',
            field=models.IntegerField(blank=True, help_text='Per-customer override in MB. Leave blank to use the package default.', null=True),
        ),
        migrations.AddField(
            model_name='customerpackage',
            name='override_max_transcriptions',
            field=models.IntegerField(blank=True, help_text='Per-customer override. Leave blank to use the package default. Use -1 for unlimited.', null=True),
        ),
    ]
