# Generated by Django 6.0.5 on 2026-05-23 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('transcript', models.TextField()),
                ('ai_prompt', models.TextField()),
                ('transcription_in_tokens', models.IntegerField(default=0)),
                ('transcription_out_tokens', models.IntegerField(default=0)),
                ('transcription_cost_usd', models.FloatField(default=0)),
                ('prompt_in_tokens', models.IntegerField(default=0)),
                ('prompt_out_tokens', models.IntegerField(default=0)),
                ('prompt_cost_usd', models.FloatField(default=0)),
                ('total_cost_usd', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
