# Generated by Django 6.0.5 on 2026-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_trialupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='mom_cost_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transcription',
            name='mom_in_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcription',
            name='mom_out_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcription',
            name='mom_report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
